name: Build & Deploy
on: [pull_request]

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_CONTAINER_REGISTRY_PASSWORD }}
  CONTAINER_REGISTRY_REPO: ghcr.io/joonvena/${{ github.event.repository.name }}
  KOLGA_IMAGE: docker.anders.fi/anders/ci-configuration:dev-buildkit-upgrade-production
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
  BUILD_ARTIFACT_FOLDER: "build_artifacts"
  SERVICE_ARTIFACT_FOLDER: "service_artifacts"
  # Default usernames and passwords for postgres setups
  # Note: These are the credentials that will be used for testing
  DATABASE_USER: user
  DATABASE_PASSWORD: testing-password
  K8S_CLUSTER_ISSUER: "certificate-letsencrypt-prod"
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        with:
          disable_cache: true

      - uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: build_artifacts/

  review:
    runs-on: ubuntu-latest
    needs: build
    name: Review
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Review-Services
        uses: andersinno/kolga-deploy-service-action@v2
        with:
          projects: JOONVENA_TUNNISTAMO
        env:
          K8S_NAMESPACE: ${{ env.repo_name}}-${{ env.pr_id }}-${{ env.ref }}
          ENVIRONMENT_URL: https://${{ env.repo_name }}-${{ env.pr_id }}-${{ env.ref }}.andersalumni.fi
          ENVIRONMENT_SLUG: ${{ env.ref }}

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        env:
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_NAMESPACE: ${{ env.repo_name}}-${{ env.pr_id }}-${{ env.ref }}
          ENVIRONMENT_URL: https://${{ env.repo_name }}-${{ env.pr_id }}-${{ env.ref }}.andersalumni.fi
          ENVIRONMENT_SLUG: ${{ env.ref }}-slug

